"""init: 建立 36 張表

Revision ID: fafac0678418
Revises: 
Create Date: 2026-09-23 12:16:08.619986

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fafac0678418'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('asset_classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('handler_class', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('body_part_mapping',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('part_code', sa.String(length=30), nullable=False),
    sa.Column('part_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required_coverage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('ui_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_code')
    )
    op.create_table('engine_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engine_type', sa.String(length=30), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('activated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('genetic_markers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('marker_code', sa.String(length=50), nullable=False),
    sa.Column('marker_name', sa.String(length=100), nullable=False),
    sa.Column('related_diseases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('related_body_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level_high', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('marker_code')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('incident_number', sa.String(length=20), nullable=False),
    sa.Column('service_name', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('trigger_event', sa.String(length=50), nullable=False),
    sa.Column('diagnosis_report', sa.Text(), nullable=True),
    sa.Column('possible_causes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_recovery_attempted', sa.Boolean(), nullable=True),
    sa.Column('auto_recovery_success', sa.Boolean(), nullable=True),
    sa.Column('recovery_action_taken', sa.String(length=100), nullable=True),
    sa.Column('recovery_error', sa.Text(), nullable=True),
    sa.Column('engineer_email_sent', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_number')
    )
    op.create_table('insurance_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_code', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('insurer_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subcategory', sa.String(length=30), nullable=True),
    sa.Column('coverage_type', sa.String(length=50), nullable=True),
    sa.Column('covered_body_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('annual_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('listed_at', sa.Date(), nullable=True),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('otp_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by', sa.String(length=36), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_models', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('asset_definitions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_class_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_class_id'], ['asset_classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('disease_risk_mapping',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('body_part_code', sa.String(length=30), nullable=False),
    sa.Column('disease_code', sa.String(length=50), nullable=False),
    sa.Column('age_risk_multiplier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gender_risk_multiplier', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('family_history_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('genetic_multiplier', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['body_part_code'], ['body_part_mapping.part_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_cache_invalidations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engine_type', sa.String(length=30), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=True),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('subscriber_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['engine_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('crawler_version_id', sa.String(length=36), nullable=True),
    sa.Column('normalizer_version_id', sa.String(length=36), nullable=True),
    sa.Column('validator_version_id', sa.String(length=36), nullable=True),
    sa.Column('matcher_version_id', sa.String(length=36), nullable=True),
    sa.Column('monte_carlo_version_id', sa.String(length=36), nullable=True),
    sa.Column('llm_version_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['crawler_version_id'], ['engine_versions.id'], ),
    sa.ForeignKeyConstraint(['llm_version_id'], ['engine_versions.id'], ),
    sa.ForeignKeyConstraint(['matcher_version_id'], ['engine_versions.id'], ),
    sa.ForeignKeyConstraint(['monte_carlo_version_id'], ['engine_versions.id'], ),
    sa.ForeignKeyConstraint(['normalizer_version_id'], ['engine_versions.id'], ),
    sa.ForeignKeyConstraint(['validator_version_id'], ['engine_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_products_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('change_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['insurance_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_cost_references',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('disease_code', sa.String(length=50), nullable=False),
    sa.Column('disease_name', sa.String(length=200), nullable=False),
    sa.Column('related_body_part', sa.String(length=30), nullable=True),
    sa.Column('cost_min', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_max', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('cost_avg', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['related_body_part'], ['body_part_mapping.part_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_code')
    )
    op.create_table('recompute_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('engine_type', sa.String(length=30), nullable=False),
    sa.Column('from_version_id', sa.String(length=36), nullable=True),
    sa.Column('to_version_id', sa.String(length=36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('affected_records', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['from_version_id'], ['engine_versions.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['engine_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('llm_provider', sa.String(length=30), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email_type', sa.String(length=50), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engine_traces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execution_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('engine_type', sa.String(length=30), nullable=False),
    sa.Column('parent_trace_id', sa.String(length=36), nullable=True),
    sa.Column('step_name', sa.String(length=100), nullable=True),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['execution_snapshot_id'], ['execution_snapshots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_trace_id'], ['engine_traces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('financial_models',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=True),
    sa.Column('emergency_fund_months', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_inputs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('user_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('data_quality', sa.String(length=20), nullable=True),
    sa.Column('market_snapshot_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_gap_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('part_code', sa.String(length=30), nullable=False),
    sa.Column('existing_coverage', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('required_coverage', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('coverage_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('state', sa.String(length=10), nullable=False),
    sa.Column('calculation_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_code'], ['body_part_mapping.part_code'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_usage_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=True),
    sa.Column('tokens_output', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_prices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_definition_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('source_status', sa.String(length=20), nullable=True),
    sa.Column('source_used', sa.String(length=50), nullable=True),
    sa.Column('source_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_level', sa.String(length=20), nullable=True),
    sa.Column('execution_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['asset_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_definition_id')
    )
    op.create_table('market_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_definition_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('validation_status', sa.String(length=20), nullable=True),
    sa.Column('execution_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['asset_definitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=100), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('failed_payment_count', sa.Integer(), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_genetic_tests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('marker_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('raw_data_encrypted', sa.Text(), nullable=True),
    sa.Column('risk_level_computed', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['marker_id'], ['genetic_markers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_health_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('family_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('has_genetic_test', sa.Boolean(), nullable=True),
    sa.Column('consent_genetic', sa.Boolean(), nullable=True),
    sa.Column('consent_genetic_at', sa.DateTime(), nullable=True),
    sa.Column('completion_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('forecast_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('input_snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('simulation_count', sa.Integer(), nullable=False),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('execution_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['input_snapshot_id'], ['forecast_inputs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['financial_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('asset_definition_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('average_cost', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['asset_definition_id'], ['asset_definitions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['financial_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insurance_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('subcategory', sa.String(length=30), nullable=True),
    sa.Column('policy_name', sa.String(length=200), nullable=False),
    sa.Column('insurer_name', sa.String(length=100), nullable=True),
    sa.Column('policy_number', sa.String(length=100), nullable=True),
    sa.Column('coverage_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('annual_premium', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('payment_period_years', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('covered_body_parts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['financial_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('liability_type', sa.String(length=20), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('monthly_payment', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['financial_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaults',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('vault_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['financial_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecast_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('metric', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('confidence_interval_low', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('confidence_interval_high', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('execution_snapshot_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['forecast_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecast_results')
    op.drop_table('vaults')
    op.drop_table('liabilities')
    op.drop_table('insurance_policies')
    op.drop_table('holdings')
    op.drop_table('forecast_runs')
    op.drop_table('user_health_profiles')
    op.drop_table('user_genetic_tests')
    op.drop_table('subscriptions')
    op.drop_table('market_snapshots')
    op.drop_table('market_prices')
    op.drop_table('llm_usage_logs')
    op.drop_table('insurance_gap_snapshots')
    op.drop_table('forecast_inputs')
    op.drop_table('financial_models')
    op.drop_table('engine_traces')
    op.drop_table('email_logs')
    op.drop_table('users')
    op.drop_table('recompute_jobs')
    op.drop_table('medical_cost_references')
    op.drop_table('insurance_products_history')
    op.drop_table('execution_snapshots')
    op.drop_table('engine_cache_invalidations')
    op.drop_table('disease_risk_mapping')
    op.drop_table('asset_definitions')
    op.drop_table('tenants')
    op.drop_table('refresh_tokens')
    op.drop_table('otp_tokens')
    op.drop_table('insurance_products')
    op.drop_table('incidents')
    op.drop_table('genetic_markers')
    op.drop_table('engine_versions')
    op.drop_table('body_part_mapping')
    op.drop_table('audit_logs')
    op.drop_table('asset_classes')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
